
Use sakila;

SELECT * from sakila.film_category;

-- 1

SELECT COUNT(fg.film_id) as Film_count, c.name as film_category FROM sakila.film_category AS fg
JOIN sakila.category AS c
ON fg.category_id = c.category_id
GROUP BY  c.name
ORDER BY   Film_count DESC;

-- 2 Retrieve the store ID, city, and country for each store.
-- cpuntry - city
-- adress_id - city_id
-- adress_id - store_id
-- store_id - store 


SELECT s.store_id, c.city,  co.country FROM sakila.city AS c
JOIN sakila.country AS co
ON c.country_id = co.country_id
JOIN sakila.address AS a
ON a.city_id = c.city_id
JOIN sakila.store as s
ON s.address_id = a.address_id;

-- 3 Calculate the total revenue generated by each store in dollars.

SELECT st.store_id, COUNT(p.amount) AS Revenue_per_store FROM sakila.payment AS p
JOIN sakila.staff AS s
ON p.staff_id = s.staff_id
JOIN sakila.store AS st
ON s.store_id = st.store_id
group by st.store_id;

-- 4 Determine the average running time of films for each category.

SELECT AVG(f.length) AS running_time, c.name AS category from sakila.film AS f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id
JOIN sakila.category AS c
ON fc.category_id = c.category_id
GROUP BY c.category_id
ORDER BY running_time DESC;


-- 5 Identify the film categories with the longest average running time.

SELECT AVG(f.length) AS running_time, c.name AS category from sakila.film AS f
JOIN sakila.film_category AS fc
ON f.film_id = fc.film_id
JOIN sakila.category AS c
ON fc.category_id = c.category_id
GROUP BY c.category_id
ORDER BY running_time DESC
LIMIT 1;

-- 6 Display the top 10 most frequently rented movies in descending order. 

SELECT COUNT(r.inventory_id) as rental_frequency, f.title from sakila.rental AS r
JOIN sakila.inventory AS i
ON r.inventory_id = i.inventory_id
JOIN sakila.film AS f
ON i.film_id = f.film_id
GROUP BY f.film_id
order by rental_frequency DESC
LIMIT 10;

-- 7 Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT film_id, title from sakila.film
WHERE title = "Academy Dinosaur";

SELECT  s.store_id, COUNT(*) from sakila.inventory AS i
JOIN sakila.store AS s
ON i.store_id = s.store_id
WHERE i.film_id = 1
GROUP BY s.store_id;

 
 

